### ISSUE TITLE
Duplicate user

### ISSUE THREAD

**Issue by AmirAliSobhGol** [geekhouseteam/yumbox#13]
when there is no token, check if the mobilephone already exists or not, if it does do not create a new user instead just send a token. but it would'nt be secure, since there is no password.
discuss it with the team

**Comment by tectual** [comment]
@Mahdiye  @RezaOwliaei 
We should have below conditions:
When token is available: Should auth the user and then proceed with **order logic**. If auth fails or user is not registered system should return Auth error message
When token is not available: Should check if any user has signed up using same phone number. If any user existed system should return an error indicating user existed and they cant register the phone. Otherwise the proceed with **order logic**

Order logic: if there is enough food to be ordered submit the order otherwise return error message and show how much food is left.

**Comment by RezaOwliaei** [comment]
It's already fixed. If there's any further issue please report.
